### ISSUE TITLE
Update docs on drone/plugin page

### ISSUE THREAD

**Issue by ispringle** [danielgormly/drone-plugin-kube#5]
The docs on drone's site [here](http://plugins.drone.io/danielgormly/drone-plugin-kube/) are not up to date. Not sure if this is something you can update or if someone w/ drone needs to be pulled in to help, but judging by the fact that it suggests pulling the v0.0.1 version, it hasn't been updated in a hot minute.

**Comment by danielgormly** [comment]
Hey yeah you can make a PR on their [drone-plugin-index](https://github.com/drone/drone-plugin-index). The `drone.md` file in this repo is up to date. They are pretty strict about the formatting. Go ahead if you want to, or I may get to it this weekend if I have time.

**Comment by malikbenkirane** [comment]
@danielgormly FWIW i've spotted an error in the reference table in `drone.md`

see https://github.com/danielgormly/drone-plugin-kube/commit/f9f8d9aa49d9ea8ea9cc9ba3f6098cbe91f570b3#r40289540

**Comment by malikbenkirane** [comment]
Opened drone/drone-plugin-index#280 - let me know what you think !

**Comment by ispringle** [comment]
That's perfect! Thanks for the work. Just got back from vacation and catching up.
